### ISSUE TITLE
encounter bug when using Derby to train/evaluate ML model

### ISSUE THREAD

**Issue by oathaha** [smartshark/promise-challenge#1]
When I ran experiment with baselines, I found that the programs stop working when they run on Derby project. Here is the error message that I encountered:

```
Traceback (most recent call last):
  File "approach.py", line 45, in <module>
    approach()
  File "approach.py", line 21, in approach
    data = load_project(path=data_path, project_name=project_name)
  File "/home/oathaha/Oat/promise-challenge/approaches/baseline_all/utils.py", line 23, in load_project
    df =  pd.read_csv(path+project_name+'.csv.gz')
  File "/home/oathaha/Oat/promise-challenge/approaches/baseline_all/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/oathaha/Oat/promise-challenge/approaches/baseline_all/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/home/oathaha/Oat/promise-challenge/approaches/baseline_all/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/oathaha/Oat/promise-challenge/approaches/baseline_all/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/opt/conda/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/conda/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached 
```

I have no idea about how to solve this. Could you please fix this problem?

**Comment by atrautsch** [comment]
Maybe the file got corrupted. I have updated the repository, can you try again?

**Comment by oathaha** [comment]
I tried using the new derby dataset. I am not sure if I can run it because the process was killed when training is done on this project.

I use 32-core cpu and 64 GB memory to train model so I am not sure if the dataset is too large to train model.

**Comment by sherbold** [comment]
Which baseline? The [random forest with data from all projects]([approaches/baseline_rf_all/approach.py) requires over 75 GB memory on my machine. It still works with less memory, but only if you have enough virtual memory (swap). The other baselines should run fine with less memory.

**Comment by oathaha** [comment]
After I looked for the reason why I cannot run the program, I found that I have less than 75 GB memory and the swap memory is quite small (2GB). So I came up with the new idea to load data.

Instead of loading all data in a dictionary and loop through it, I think the code should load dataset for particular project. Here is my code in baseline_rf_all/approach.py .

  ```
  for project in list_all_projects(path=data_path):
        print(project)

        data = load_project(data_path, project)
        projects = {}
        projects[project] = data # prepare data like this so it can be used with prepare_within_project_data() function
```

I think this code is similar to baseline_rf_wp/approach.py so I suggest that the code for loading data in baseline_rf_wf/approach.py should be used in baseline_rf_all/approach.py .

**Comment by sherbold** [comment]
The difference is intentional and cannot be avoided:

- baseline_rf_all trains a model using the data from *all* projects.
- baseline_rf_wp trains a model using only old data from the project for which defects are predicted. 

Switching the loading code is more or less the same as switching from using all data to using within-project data. The approach using all data cannot work with less memory, because the data is just so large. 

Please note that you do not have to be able to run all baselines on your machines to participate. Our baseline rf_all is not very efficient. Here are some things you can do to work with less memory:
- Build a within project model based on the rf_wp template
- Build a mixed cross project model with a data selection strategy to find a subset of instances or based on a subset of features, so you do not require as much memory.

**Comment by oathaha** [comment]
Thank you for your answer. However, I think you should provide the result of baselines just in case someone wants to evaluate the result with baselines but he/she cannot run the baseline on his/her own machine.
